# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('YAVP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelstop',
            options={'ordering': ['-StartDate']},
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['Name'], name='District_name_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['Name', 'City'], name='District_City_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['Name'], name='City_name_idx'),
        ),
    ]
