# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('YAVP', '0002_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAVP.Continent')),
            ],
        ),
    ]
