# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('YAVP', '0005_auto_20170530_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Flag',
            field=models.ImageField(default=None, upload_to='Flags/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='Country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='YAVP.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAVP.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAVP.Continent'),
        ),
    ]
