# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('YAVP', '0007_auto_20170530_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='EndArra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EndArra',
                                    to='YAVP.Area'),
        ),
        migrations.AddField(
            model_name='travel',
            name='EndCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EndCity',
                                    to='YAVP.City'),
        ),
        migrations.AddField(
            model_name='travel',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='StartArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StartArea',
                                    to='YAVP.Area'),
        ),
        migrations.AddField(
            model_name='travel',
            name='StartCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StartCity',
                                    to='YAVP.City'),
        ),
        migrations.AddField(
            model_name='travel',
            name='StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YAVP.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAVP.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAVP.Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Flag',
            field=models.ImageField(null=True, upload_to='Flags/'),
        ),
    ]
